apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: k8g9ur5pl-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: k8g9ur5pl-nodejs 
  name: k8g9ur5pl-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: k8g9ur5pl-nodejs 
